### ISSUE TITLE
Remove newsletter checkbox from form (temporarily)

### ISSUE THREAD

**Issue by danielcb29** [angular-medellin/form#14]
Remove newsletter checkbox option from from

 Image attached.
<img width="949" alt="angmed" src="https://user-images.githubusercontent.com/8260962/28528562-b1bd63c6-7053-11e7-9ad6-716ff40af1ba.PNG">

**Comment by jdjuan** [comment]
Awe! @Shinkei can tackle it down in no time! 🏎 🏎 🏎

**Comment by Shinkei** [comment]
hehehe it was an easy change :blush:
