### ISSUE TITLE
Create Node service to send confirmation emails 📩

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/form#3]
Let's create an backend service that send an email using gmail SMTP.  It takes four parameters:

1. Security token (this to authorize the client [our app] consuming the endpoint)
2. Email (user's email)
3. Message Subject
4. Message Body

## Concerns 

- Use `Express` or `Koa` or any other framework to create the services.
- Use Heroku to deploy the app or any other hosting you prefer. If you need one, let me know
- We might reuse this server for the @angular-medellin/newsletter-team 

## Juan's tasks:

- [x] Create a Gmail account for the community and give you the credentials so you can put them on the server.
- [x] Create a repository to hold the backend server

PS: Use this test project as a reference to send the email using gmail:
https://github.com/jdjuan/shared-lunch/blob/backend-api/server.js

**Comment by jdjuan** [comment]
Here's your backend repo: https://github.com/angular-medellin/backend 👍

**Comment by alejandronanez** [comment]
Just for the record, we ended up deciding to use Mailchimp for handling all email related stuff. We will have a node service to get all subscriber from a MC list using this project https://github.com/angular-medellin/backend/pull/2
