### ISSUE TITLE
Search frontend templates for the form 😎

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/form#5]
Open a issue with the top three most beautiful HTML-and-CSS only templates you find online. After a decision is made, create a PR adding it to the `app` component of the application.

**Comment by alvaromartinez986** [comment]
These are the top 3 form templates that I found:

1. https://codepen.io/khadkamhn/pen/ZGvPLo
2. https://codepen.io/GrandvincentMarion/pen/KpmgOe/
3. https://codepen.io/matthu185/pen/myyvgr

Others that I found it are (In case that you don like it): 

- https://codepen.io/markmurray/pen/JsAhx/
- https://codepen.io/arianalynn/pen/mPWdPZ
- https://codepen.io/lancebush/pen/agxne
- https://codepen.io/khadkamhn/pen/ZGvPLo

**Comment by alvaromartinez986** [comment]
I vote for the 1st option

**Comment by Shinkei** [comment]
Numero 2 :+1:

**Comment by danielcb29** [comment]
Number 1 is really nice. 🥇

**Comment by jdjuan** [comment]
First one I like 😄

**Comment by jdjuan** [comment]
That's 3 out of 5 votes. Please proceed with the mission using (1) 🦅 

Create a branch where you implement that template in a component!

**Comment by danielcb29** [comment]
@alvaromartinez986 Any question please let me know, I can give you a hand ✋

**Comment by jdjuan** [comment]
@alvaromartinez986 no olvides que no sólo necesitamos el html y css del formulario, también necesitamos el template para el resto, échale un ojo a https://html5up.net/ . Sobre uno de ellos podrías montar el formulario, o re-considerar uno de esos templates que ya tenga el formulario listo 😄

**Comment by alvaromartinez986** [comment]
Okay, I will check it, and at night I will post it the three better.

**Comment by Shinkei** [comment]
Guys maybe this could be helpfull https://startbootstrap.com/

**Comment by alvaromartinez986** [comment]
The PR is ready, but according to the talk wit @jdjuan, instead of using a form template, we can use a landing page has a form included like:

1. https://html5up.net/story
 
2. https://html5up.net/forty
 
3. https://html5up.net/solid-state
 
4. https://html5up.net/directive
 
 
this landing page can be combined with the form (That we have already decided) and aggregated it by a modal 
 
5. https://html5up.net/spectral 

6. https://html5up.net/photon

I will be waiting for the decision

PD: I vote for the first one.

**Comment by danielcb29** [comment]
All of it are awesome! 🎉 ,  My favorite stack are: 

1) 2 
2) 3
3) 1
4) 6
.... 

Or anyone , I really like all of it 😄

**Comment by alvaromartinez986** [comment]
This is a view of the form: 

![image](https://user-images.githubusercontent.com/9259335/27491993-275f2342-580a-11e7-8cc4-49e1fa415803.png)

**Comment by danielcb29** [comment]
@alvaromartinez986  nice!

**Comment by jdjuan** [comment]
I vote for 2 (Forty) just as @danielcb29 ! Let's go for that one, I think it will work just fine! 👍 I am eager to see it 😁

**Comment by danielcb29** [comment]
@jdjuan @alvaromartinez986 this issue is merged now, next step is create a new issue to integrate MailChimp with out Angular Project 😄  🚀
